steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}",
        "-t",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest",
        "--region",
        "us-east4",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--service-account=${_SERVICE_ACCOUNT}"
      ]
options:
  logging: CLOUD_LOGGING_ONLY